[workspace]
resolver = "3"
members = ["cli", "doot"]

[workspace.package]
description = "Doot programming language"
license = "MIT"
categories = ["compilers"]
repository = "https://github.com/lspita/doot"
