name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    name: Format, Build & Test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Format
      run: cargo fmt --check
    - name: Build
      run: cargo build
    - name: Test
      run: cargo test
